# Generated by Django 3.2.18 on 2023-02-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPhotoFrame',
            fields=[
                ('frame_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('width', models.BooleanField(default=False, null=True)),
                ('height', models.BooleanField(default=False, null=True)),
                ('frame_background', models.ImageField(blank=True, default='', upload_to='frame_photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='frame_background',
        ),
        migrations.AddField(
            model_name='film',
            name='myPhotoFrame',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photo_film', to='film.myphotoframe'),
        ),
    ]
